#! /bin/sh
### BEGIN INIT INFO
# Provides:          eng10032lab08_1
# Required-Start:    
# Should-Start:      
# Required-Stop:     
# Default-Start:     S
# Default-Stop:
# Short-Description: Configures SPI bus for Lab 08.
# Description:       Configures SPI bus for Lab 08.
### END INIT INFO

boardId=`cat /sys/devices/virtual/dmi/id/board_name`

case "$1" in
  start|restart|force-reload)
    case $boardId in
      "Galileo")
	# Configures IO10 for SPI #SS
	#	gpio42=0 (IO10 is #SS)	
	#	gpio16 (output)
	if [ ! -d /sys/class/gpio/gpio42 ] ; then
	    echo -n "42" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio42/direction
	echo -n "0" > /sys/class/gpio/gpio42/value

	if [ ! -d /sys/class/gpio/gpio16 ] ; then
	    echo -n "16" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio16/direction
	echo -n "1" > /sys/class/gpio/gpio16/value

	# Configures IO11 for SPI MOSI
	#	gpio43=0 (IO11 is MOSI)
	if [ ! -d /sys/class/gpio/gpio43 ] ; then
	    echo -n "43" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio43/direction
	echo -n "0" > /sys/class/gpio/gpio43/value

	# Configures IO12 for SPI MISO
	#	gpio54=0 (IO12 is MISO}
	if [ ! -d /sys/class/gpio/gpio54 ] ; then
	    echo -n "54" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio54/direction
	echo -n "0" > /sys/class/gpio/gpio54/value

	# Configure IO13 for SPI SCLK
	#	gpio55=0 (IO13 is SCLK)
	if [ ! -d /sys/class/gpio/gpio55 ] ; then
	    echo -n "55" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio55/direction
	echo -n "0" > /sys/class/gpio/gpio55/value
        ;;
      "GalileoGen2")
	# Configures IO10 for SPI #SS
	#	gpio26=0 (output)
	#	gpio27=1 (pull-up)
	#	gpio74=0 (IO10 is GPIO)
	if [ ! -d /sys/class/gpio/gpio26 ] ; then
	    echo -n "26" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio26/direction
	echo -n "0" > /sys/class/gpio/gpio26/value
	
	if [ ! -d /sys/class/gpio/gpio27 ] ; then
	    echo -n "27" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio27/direction
	echo -n "1" > /sys/class/gpio/gpio27/value
	
	if [ ! -d /sys/class/gpio/gpio74 ] ; then
	    echo -n "74" > /sys/class/gpio/export
	fi
	echo -n "0" > /sys/class/gpio/gpio74/value
	
	# Configures IO11 for SPI MOSI
	#	gpio24=0 (output)
	#	gpio25=input (floating)
	#	gpio44=1 (IO11 is SPI)
	#	gpio72=0 (IO11 is SPI)
	if [ ! -d /sys/class/gpio/gpio24 ] ; then
	    echo -n "24" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio24/direction
	echo -n "0" > /sys/class/gpio/gpio24/value
	
	if [ ! -d /sys/class/gpio/gpio25 ] ; then
	    echo -n "25" > /sys/class/gpio/export
	fi
	echo -n "in" > /sys/class/gpio/gpio25/direction
	
	if [ ! -d /sys/class/gpio/gpio44 ] ; then
	    echo -n "44" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio44/direction
	echo -n "1" > /sys/class/gpio/gpio44/value
	
	if [ ! -d /sys/class/gpio/gpio72 ] ; then
	    echo -n "72" > /sys/class/gpio/export
	fi
	echo -n "0" > /sys/class/gpio/gpio72/value

	# Configures IO12 for SPI MISO
	#	gpio42=1 (input)
	#	gpio43=input (floating)
	if [ ! -d /sys/class/gpio/gpio42 ] ; then
	    echo -n "42" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio42/direction
	echo -n "1" > /sys/class/gpio/gpio42/value
	
	if [ ! -d /sys/class/gpio/gpio43 ] ; then
	    echo -n "43" > /sys/class/gpio/export
	fi
	echo -n "in" > /sys/class/gpio/gpio43/direction

	# Configure IO13 for SPI SCLK
	#	gpio30=0 (output)
	#	gpio31=0 (pull-down, SCLK mode 0)
	#	gpio46=1 (IO13 is SPI)
	if [ ! -d /sys/class/gpio/gpio30 ] ; then
	    echo -n "30" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio30/direction
	echo -n "0" > /sys/class/gpio/gpio30/value
	
	if [ ! -d /sys/class/gpio/gpio31 ] ; then
	    echo -n "31" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio31/direction
	echo -n "0" > /sys/class/gpio/gpio31/value
	
	if [ ! -d /sys/class/gpio/gpio46 ] ; then
	    echo -n "46" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio46/direction
	echo -n "1" > /sys/class/gpio/gpio46/value
	;;
    esac
    chgrp spi /dev/spidev1.0
    chmod g+rw /dev/spidev1.0
    ;;
  stop)
    case $boardId in
      "Galileo")
	echo -n "0" > /sys/class/gpio/gpio42/value
	echo -n "42" > /sys/class/gpio/unexport

	echo -n "in" > /sys/class/gpio/gpio16/direction
	echo -n "16" > /sys/class/gpio/unexport

	echo -n "0" > /sys/class/gpio/gpio43/value
	echo -n "43" > /sys/class/gpio/unexport

	echo -n "0" > /sys/class/gpio/gpio54/value
	echo -n "54" > /sys/class/gpio/unexport

	echo -n "0" > /sys/class/gpio/gpio55/value
	echo -n "55" > /sys/class/gpio/unexport
        ;;
      "GalileoGen2")
	echo -n "1" > /sys/class/gpio/gpio26/value
	echo -n "26" > /sys/class/gpio/unexport
	
	echo -n "in" > /sys/class/gpio/gpio27/direction
	
	echo -n "74" > /sys/class/gpio/unexport
	
	echo -n "1" > /sys/class/gpio/gpio24/value
	echo -n "24" > /sys/class/gpio/unexport
	
	echo -n "25" > /sys/class/gpio/unexport

	echo -n "0" > /sys/class/gpio/gpio44/value
	echo -n "44" > /sys/class/gpio/unexport
	
	echo -n "72" > /sys/class/gpio/unexport

	echo -n "42" > /sys/class/gpio/unexport

	echo -n "43" > /sys/class/gpio/unexport

	echo -n "0" > /sys/class/gpio/gpio46/value
	echo -n "46" > /sys/class/gpio/unexport
	
	echo -n "in" > /sys/class/gpio/gpio31/direction
	echo -n "31" > /sys/class/gpio/unexport
	
	echo -n "1" > /sys/class/gpio/gpio30/value
	echo -n "30" > /sys/class/gpio/unexport
	;;
    esac
    ;;
  status)
    ;;
  *)
    echo -n "Usage: $0 "
    echo "{start|stop|restart|force-reload|status}"
    exit 1
    ;;
esac

exit 0