#! /bin/sh
### BEGIN INIT INFO
# Provides:          eng10032p1
# Required-Start:    
# Should-Start:      
# Required-Stop:     
# Default-Start:     S
# Default-Stop:
# Short-Description: Configures GPIO for P1.
# Description:       Configures GPIO for P1.
### END INIT INFO

boardId=`cat /sys/devices/virtual/dmi/id/board_name`

case "$1" in
  start|restart|force-reload)
    case $boardId in
      "Galileo")
				# gpio44 = in = neither pull-up nor pull-down
        if [ ! -d /sys/class/gpio/gpio44 ] ; then
          echo -n "44" > /sys/class/gpio/export
        fi
        echo -n "in" > /sys/class/gpio/gpio44/direction
        
        # gpio37 = 0 = AD0
        if [ ! -d /sys/class/gpio/gpio37 ] ; then
          echo -n "37" > /sys/class/gpio/export
        fi
        echo -n "out" > /sys/class/gpio/gpio37/direction
        echo -n "0" > /sys/class/gpio/gpio37/value

				# ADC AO configuration
				chgrp adc /sys/bus/iio/devices/iio:device0/in_voltage0_raw
				chmod g+r /sys/bus/iio/devices/iio:device0/in_voltage0_raw
				chgrp adc /sys/bus/iio/devices/iio:device0/in_voltage0_scale
				chmod g+r /sys/bus/iio/devices/iio:device0/in_voltage0_scale
        ;;
      "GalileoGen2")
				# Pull-up GPIO
				if [ ! -d /sys/class/gpio/gpio49 ] ; then
					echo -n "49" > /sys/class/gpio/export
				fi
				# No pull-up neither pull-down
				echo -n "in" > /sys/class/gpio/gpio19/direction

				# ADC AO configuration
				chgrp adc /sys/bus/iio/devices/iio:device0/in_voltage0_raw
				chmod g+r /sys/bus/iio/devices/iio:device0/in_voltage0_raw
				chgrp adc /sys/bus/iio/devices/iio:device0/in_voltage0_scale
				chmod g+r /sys/bus/iio/devices/iio:device0/in_voltage0_scale
	;;
    esac
    ;;
  stop)
    case $boardId in
      "Galileo")
	    echo -n "44" > /sys/class/gpio/unexport
	    echo -n "37" > /sys/class/gpio/unexport
		;;
      "GalileoGen2")
			echo -n "49" > /sys/class/gpio/unexport
	;;
    esac
    ;;
  status)
    	ls -d /sys/class/gpio/gpio*
	;;
  *)
	echo -n "Usage: $0 " 
	echo "{start|stop|restart|force-reload|status}"
	exit 1
	;;
esac

exit 0
