#! /bin/sh
### BEGIN INIT INFO
# Provides:          eng10032p1
# Required-Start:    
# Should-Start:      
# Required-Stop:     
# Default-Start:     S
# Default-Stop:
# Short-Description: Configures GPIO for P1.
# Description:       Configures GPIO for P1.
### END INIT INFO

boardId=`cat /sys/devices/virtual/dmi/id/board_name`

case "$1" in
  start|restart|force-reload)
    case $boardId in
      "GalileoGen2")
				############################################################################################
				# IO2 output 
				## Left Shifter GPIO
				if [ ! -d /sys/class/gpio/gpio34 ] ; then
					echo -n "34" > /sys/class/gpio/export
				fi
				echo -n "out" > /sys/class/gpio/gpio34/direction
				echo -n "0" > /sys/class/gpio/gpio34/value

				## 22k Pull-up GPIO
				if [ ! -d /sys/class/gpio/gpio35 ] ; then
					echo -n "35" > /sys/class/gpio/export
				fi

				### Pull-up
				echo -n "out" > /sys/class/gpio/gpio35/direction
				echo -n "1" > /sys/class/gpio/gpio35/value

				## Pin Mux 1 GPIO
				if [ ! -d /sys/class/gpio/gpio77 ] ; then
					echo -n "77" > /sys/class/gpio/export
				fi

				echo -n "out" > /sys/class/gpio/gpio77/direction
				echo -n "1" > /sys/class/gpio/gpio77/value

				## Linux
				if [ ! -d /sys/class/gpio/gpio13 ] ; then
					echo -n "13" > /sys/class/gpio/export
				fi

				## Permissions
				chgrp gpio /sys/class/gpio/gpio13/value
				chmod g+rw /sys/class/gpio/gpio13/value

				############################################################################################
				# IO6 input 
				## Left Shifter GPIO
				if [ ! -d /sys/class/gpio/gpio20 ] ; then
					echo -n "20" > /sys/class/gpio/export
				fi
				echo -n "in" > /sys/class/gpio/gpio20/direction
				echo -n "0" > /sys/class/gpio/gpio20/value

				## 22k Pull-up GPIO
				if [ ! -d /sys/class/gpio/gpio21 ] ; then
					echo -n "21" > /sys/class/gpio/export
				fi

				### No pull-up neither pull-down
				echo -n "in" > /sys/class/gpio/gpio21/direction

				## Pin Mux 1 GPIO
				if [ ! -d /sys/class/gpio/gpio68 ] ; then
					echo -n "68" > /sys/class/gpio/export
				fi

				echo -n "in" > /sys/class/gpio/gpio68/direction
				echo -n "0" > /sys/class/gpio/gpio68/value

				## Linux
				if [ ! -d /sys/class/gpio/gpio1 ] ; then
					echo -n "1" > /sys/class/gpio/export
				fi

				## Permissions
				chgrp gpio /sys/class/gpio/gpio1/value
				chmod g+rw /sys/class/gpio/gpio1/value

				############################################################################################
				# IO4 Interrupt mode
				## Left Shifter GPIO
				if [ ! -d /sys/class/gpio/gpio36 ] ; then
					echo -n "36" > /sys/class/gpio/export
				fi
				echo -n "out" > /sys/class/gpio/gpio36/direction
				echo -n "1" > /sys/class/gpio/gpio36/value

				## 22k Pull-up GPIO
				if [ ! -d /sys/class/gpio/gpio37 ] ; then
					echo -n "37" > /sys/class/gpio/export
				fi

				### Pull-down
				echo -n "out" > /sys/class/gpio/gpio37/direction
				echo -n "1" > /sys/class/gpio/gpio37/value

				## Linux
				if [ ! -d /sys/class/gpio/gpio6 ] ; then
					echo -n "6" > /sys/class/gpio/export
				fi

				## Permissions
				chgrp gpio /sys/class/gpio/gpio6/value
				chmod g+r /sys/class/gpio/gpio6/value
				chgrp gpio /sys/class/gpio/gpio6/edge
				chmod g+rw /sys/class/gpio/gpio6/edge

				############################################################################################
				# PWM 3
				## Left Shifter GPIO
				if [ ! -d /sys/class/gpio/gpio18 ] ; then
					echo -n "18" > /sys/class/gpio/export
				fi

				echo -n "out" > /sys/class/gpio/gpio18/direction
				echo -n "0" > /sys/class/gpio/gpio18/value

				## 22k Pull-up GPIO
				if [ ! -d /sys/class/gpio/gpio19 ] ; then
					echo -n "19" > /sys/class/gpio/export
				fi

				### No pull up or pull down
				echo -n "in" > /sys/class/gpio/gpio19/direction


				# Pin Mux 1 GPIO  
				if [ ! -d /sys/class/gpio/gpio66 ] ; then
					echo -n "66" > /sys/class/gpio/export
				fi
				echo -n "1" > /sys/class/gpio/gpio66/value

				# PWM3 configuration - Linux
				if [ ! -d /sys/class/pwm/pwmchip0/pwm3 ] ; then
						echo -n "3" > /sys/class/pwm/pwmchip0/export
				fi

				## Permissions
				chgrp pwm /sys/class/pwm/pwmchip0/device/pwm_period
				chmod g+w /sys/class/pwm/pwmchip0/device/pwm_period
				chgrp pwm /sys/class/pwm/pwmchip0/pwm3/duty_cycle
				chmod g+w /sys/class/pwm/pwmchip0/pwm3/duty_cycle
				chgrp pwm /sys/class/pwm/pwmchip0/pwm3/enable
				chmod g+w /sys/class/pwm/pwmchip0/pwm3/enable

				############################################################################################
				# ADC Modo disparo unico A0
				## Pull-up GPIO
				if [ ! -d /sys/class/gpio/gpio49 ] ; then
					echo -n "49" > /sys/class/gpio/export
				fi
				### No pull-up neither pull-down
				echo -n "in" > /sys/class/gpio/gpio19/direction

				## ADC AO configuration
				chgrp adc /sys/bus/iio/devices/iio:device0/in_voltage0_raw
				chmod g+r /sys/bus/iio/devices/iio:device0/in_voltage0_raw
				chgrp adc /sys/bus/iio/devices/iio:device0/in_voltage0_scale
				chmod g+r /sys/bus/iio/devices/iio:device0/in_voltage0_scale

				############################################################################################
	;;
    esac
    ;;
  stop)
    case $boardId in
      "GalileoGen2")
				# IO2 output
				echo -n "in" > /sys/class/gpio/gpio34/direction
				echo -n "1" > /sys/class/gpio/gpio34/value
				echo -n "34" > /sys/class/gpio/unexport
				echo -n "in" > /sys/class/gpio/gpio35/direction
				echo -n "1" > /sys/class/gpio/gpio35/value
				echo -n "35" > /sys/class/gpio/unexport
				echo -n "in" > /sys/class/gpio/gpio77/direction
				echo -n "1" > /sys/class/gpio/gpio77/value
				echo -n "77" > /sys/class/gpio/unexport
				echo -n "13" > /sys/class/gpio/unexport
				# IO6 input
				echo -n "in" > /sys/class/gpio/gpio20/direction
				echo -n "1" > /sys/class/gpio/gpio20/value
				echo -n "20" > /sys/class/gpio/unexport
				echo -n "in" > /sys/class/gpio/gpio21/direction
				echo -n "1" > /sys/class/gpio/gpio21/value
				echo -n "21" > /sys/class/gpio/unexport
				echo -n "in" > /sys/class/gpio/gpio68/direction
				echo -n "1" > /sys/class/gpio/gpio68/value
				echo -n "68" > /sys/class/gpio/unexport
				echo -n "1" > /sys/class/gpio/unexport
				# ADC
				echo -n "49" > /sys/class/gpio/unexport
				# IO4 Interrupt mode
				echo -n "in" > /sys/class/gpio/gpio36/direction
				echo -n "1" > /sys/class/gpio/gpio36/value
				echo -n "36" > /sys/class/gpio/unexport
				echo -n "in" > /sys/class/gpio/gpio35/direction
				echo -n "1" > /sys/class/gpio/gpio35/value
				echo -n "35" > /sys/class/gpio/unexport
				echo -n "6" > /sys/class/gpio/unexport
				# PWM 3
				echo -n "in" > /sys/class/gpio/gpio18/direction
				echo -n "1" > /sys/class/gpio/gpio18/value
				echo -n "18" > /sys/class/gpio/unexport
				echo -n "in" > /sys/class/gpio/gpio19/direction
				echo -n "1" > /sys/class/gpio/gpio19/value
				echo -n "19" > /sys/class/gpio/unexport
				echo -n "in" > /sys/class/gpio/gpio66/direction
				echo -n "1" > /sys/class/gpio/gpio66/value
				echo -n "66" > /sys/class/gpio/unexport
				echo -n "3" > /sys/class/pwm/pwmchip0/unexport
	;;
    esac
    ;;
  status)
    	ls -d /sys/class/gpio/gpio*
	;;
  *)
	echo -n "Usage: $0 " 
	echo "{start|stop|restart|force-reload|status}"
	exit 1
	;;
esac

exit 0
