#! /bin/sh
### BEGIN INIT INFO
# Provides:          eng10032lab03_1
# Required-Start:    
# Should-Start:      
# Required-Stop:     
# Default-Start:     S
# Default-Stop:
# Short-Description: Configures GPIO for Lab 03.
# Description:       Configures GPIO for Lab 03.
### END INIT INFO

boardId=`cat /sys/devices/virtual/dmi/id/board_name`

case "$1" in
  start|restart|force-reload)
    case $boardId in
      "Galileo")
		;;
      "GalileoGen2")
	# Pin Mux 1 GPIO  
	if [ ! -d /sys/class/gpio/gpio66 ] ; then
	    echo -n "66" > /sys/class/gpio/export
	fi
	echo -n "1" > /sys/class/gpio/gpio66/value
	
	# Left Shifter GPIO
	if [ ! -d /sys/class/gpio/gpio18 ] ; then
	    echo -n "18" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio18/direction
	echo -n "0" > /sys/class/gpio/gpio18/value

	# Pull-up GPIO
	if [ ! -d /sys/class/gpio/gpio19 ] ; then
		echo -n "19" > /sys/class/gpio/export
	fi
	echo -n "in" > /sys/class/gpio/gpio19/direction

	# PWM3 configuration
	if [ ! -d /sys/class/pwm/pwmchip0/pwm3 ] ; then
	    echo -n "3" > /sys/class/pwm/pwmchip0/export
	fi

	chgrp pwm /sys/class/pwm/pwmchip0/device/pwm_period
	chmod g+rw /sys/class/pwm/pwmchip0/device/pwm_period
	chgrp pwm /sys/class/pwm/pwmchip0/pwm3/duty_cycle
	chmod g+r /sys/class/pwm/pwmchip0/pwm3/duty_cycle
	chgrp pwm /sys/class/pwm/pwmchip0/pwm3/enable
	chmod g+r /sys/class/pwm/pwmchip0/pwm3/enable
	;;
    esac
    ;;
  stop)
    case $boardId in
      "Galileo")
		;;
      "GalileoGen2")
    	echo -n "0" > /sys/class/gpio/pwm/pwmchip0/pwm3/enable
    	echo -n "3" > sys/class/gpio/pwm/pwmchip0/unexport
    	echo -n "1" > /sys/class/gpio/gpio18/value
		echo -n "in" > /sys/class/gpio/gpio18/direction
    	echo -n "1" > /sys/class/gpio/gpio66/value
    	echo -n "in" > /sys/class/gpio/gpio66/direction
	echo -n "18" > /sys/class/gpio/unexport
	echo -n "19" > /sys/class/gpio/unexport
	echo -n "66" > /sys/class/gpio/unexport
	;;
    esac
    ;;
  status)
    	ls -d /sys/class/gpio/gpio*
	;;
  *)
	echo -n "Usage: $0 " 
	echo "{start|stop|restart|force-reload|status}"
	exit 1
	;;
esac

exit 0